python_stack/django/semi_restful_routes/apps/products/urls.py
from django.conf.urls import url
from . import views

app_name = 'products'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^new$', views.new, name='new'), 
	url(r'^create$', views.create, name='create'),
	url(r'^show/(?P<id>\d+)$', views.show, name='show'),
	url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'), 
	url(r'^update/(?P<id>\d+)$', views.update, name='update'),
	url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy')
]

python_stack/django/semi_restful_routes/semi_restful_routes/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.products.urls', namespace='products')),
]

python_stack/django/semi_restful_routes/apps/products/models.py
from __future__ import unicode_literals

from django.db import models

import re

DIGIT_REGEX = re.compile(r'.*[^0-9].*')

# Create your models here.
class ProductManager(models.Manager):
	def add_product(self, data):
		#first things first: validations!
		name = data['name']
		description = data['description']
		errors = []

		if len(data['price']) < 1:
			errors.append('All products must have a price!')
		elif not data['price'].isdigit():
			errors.append('Price must be a number!')
		else:
			price = int(data['price'])

		if len(name) < 1 or not name.isalpha():
			errors.append('Please put a valid product name!')

		if len(description) < 1:
			errors.append('Please describe your product!')

		#return errors else create new product
		if errors:
			return (False, errors)
		else:
			errors.append(name+' was successfully added!')
			new_product = Product.objects.create(name=name, description=description, price=price)
			return (True, new_product)

	def update_product(self, id, data):
		#validations
		name = data['name']
		description = data['description']
		price = int(data['price'])
		errors = []

		if len(name) < 1 or not name.isalpha():
			errors.append('Please put a valid product name!')

		if len(description) < 1:
			errors.append('Please describe your product!')

		if len(data['price']) < 1:
			errors.append('All products must have a price!')
		print data

		#return errors else create new product
		if errors:
			return (False, errors)
		else:
			errors.append(name+' successfully updated!')
			product = self.get(id=id)
			product.name = name
			product.description = description
			product.price = price
			product.save()
			return(True, errors)




class Product(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(max_length=1000)
	price = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)	
	objects = ProductManager()

python_stack/django/semi_restful_routes/apps/products/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Product

# Create your views here.
def index(request):
	context = {
		'title': 'Products Home',
		'data': Product.objects.all()
	}
	return render(request, 'products/index.html', context)

def new(request):
	context = {
		'title': 'Add Product'
	}
	return render(request, 'products/new.html', context)

def create(request):
	if request.method == 'POST':
		data = {
			'name': request.POST['name'],
			'description': request.POST['description'],
			'price': request.POST['price'],
		}

		valid, response = Product.objects.add_product(data)

		if not valid:
			for error in response:
				messages.error(request, error)
			return redirect('products:new')
		else:
			return redirect('products:index')

	return redirect('products:index')

def show(request, id):
	context = {
		'title': 'Ohhh Ahhhh',
		'product': Product.objects.get(id=id)
	}
	return render(request, 'products/show.html', context)

def edit(request, id):
	context = {
		'title': 'Edit Page',
		'product': Product.objects.get(id=id)
	}
	return render(request, 'products/edit.html', context)

def update(request, id):
	if request.method =='POST':
		data = {
			'name': request.POST['name'],
			'description': request.POST['description'],
			'price': request.POST['price'],
		}
		valid, response = Product.objects.update_product(id, data)

		if not valid:
			for error in response:
				messages.error(request, error)
			return redirect('products:edit')
		else:
			return redirect('products:index')
	else:
		return redirect('products:index')

def destroy(request, id):
	product = Product.objects.get(id=id)
	product.delete()
	return redirect('products:index')
	

python_stack/django/semi_restful_routes/apps/products/templates/products/edit.html
<!DOCTYPE html>
	<html>
	<head>
		<title>{{ title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/skeleton.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/normalize.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/styles.css' %}">
	</head>
	<body>
		<form action="{% url 'products:update' product.id %}" method="POST">
			{% csrf_token %}
			<h1>{{ product.name }}</h1>
			<label>Name:</label>
			<input type="text" name="name" value="{{ product.name }}">
			<label>Description:</label>
			<input type="text" name="description" value="{{ product.description }}">
			<label>Price:</label>
			<input type="text" name="price" value="{{ product.price }}">
			<input type="submit" value="UPDATE">
		</form>
	</body>
</html>

python_stack/django/semi_restful_routes/apps/products/templates/products/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/skeleton.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/normalize.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/styles.css' %}">
	</head>
	<body>
		<h1>Products</h1>
		{% if messages%}
			{% for msg in messages %}
				<p class="errors">{{ msg }}</p>
			{% endfor %}
		{% endif %}
		<table>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Price</th>
				<th>Action</th>
			</tr>
			{% if data %}
				{% for product in data %}
					<tr>
						<td>{{ product.name }}</td>
						<td>{{ product.description }}</td>
						<td>{{ product.price }}</td>
						<td><a href="{% url 'products:show' product.id  %}">Show</a></td>
						<td><a href="{% url 'products:edit' product.id %}">Edit</a></td>
						<td><a href="{% url 'products:destroy' product.id %}">Delete</a></td>
					</tr>
				{% endfor %}
			{% endif %}
		</table>
		<a href="{% url 'products:new' %}">Add a Product</a>
		{% block body %}{% endblock %}
	</body>
</html>

python_stack/django/semi_restful_routes/apps/products/templates/products/new.html
{% extends "./index.html"%}
{% block body %}
	<h5>Add a Product!</h5>
	<div id="add-product">
		<form action="{% url 'products:create' %}", method="POST">
		 	{% csrf_token %}
			<label>Name:</label>
			<input type="text" name="name">
			<label>Description:</label>
			<input type="text" name="description">
			<label>Price:</label>
			<input type="text" name="price">
			<input type="submit" value="Create">
		</form>
		<a href="{%  url 'products:index' %}">Cancel</a>
	</div>
{% endblock %}

python_stack/django/semi_restful_routes/apps/products/templates/products/show.html
<!DOCTYPE html>
	<html>
	<head>
		<title>{{ title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/skeleton.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/normalize.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'products/css/styles.css' %}">
	</head>
	<body>
		<h1>{{ product.name }}</h1>
		<label>Name: {{ product.name }}</label>
		<label>Description: {{ product.description }}</label>
		<label>Price: {{ product.price }}</label>
		<a href="{% url 'products:edit' product.id %}">Edit</a>
		<a href="{% url 'products:index' %}">Back</a>
	</body>
</html>