python_stack/django/main4/apps/test_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^blogs$', views.blogs),
    url(r'^comments/(?P<id>\d+)', views.comments)
]

python_stack/django/main4/main4/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.test_app.urls')),
]

python_stack/django/main4/apps/test_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Blog(models.Model):
	title = models.CharField(max_length=100)
	blog = models.TextField(max_length=1000)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
	blog = models.ForeignKey(Blog)
	comment = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

python_stack/django/main4/apps/test_app/views.py
from django.shortcuts import render, redirect
from .models import Blog, Comment

# Create your views here.
def index(request):
	context = {
		'blogs': Blog.objects.all(),
		#SELECT * FROM Blog
	}
	return render(request, 'test_app/index.html', context)

def blogs(request):
	#using ORM
	Blog.objects.create(title=request.POST['title'], blog=request.POST['blog'])
	#insert into blogs (title,blog, created_at, updated_at) VALUES (title, blog, now(), now())
	return redirect('/')

def comments(request, id):
	blog = Blog.objects.get(id=id)
	Comment.objects.create(comment=request.POST['comment'], blog=blog)

	return redirect('/')

python_stack/django/main4/apps/test_app/templates/test_app/index.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<h1>Hello World</h1>
		{% for blog in blogs %}
			<h5>{{blog.title}}</h5>
			<p>{{blog.blog}}</p>
			{% for comment in blog.comment_set.all %}
				<p>{{comment.comment}}</p>
			{% endfor %}
			<form action="/comments/{{blog.id}}" method="POST">
				{% csrf_token %} 
				<textarea name="comment" rows="8" cols="40"></textarea>
				<input type="submit" value="ENTER BLOG COMMENT">
			</form>
		{% endfor %}


		<form action="/blogs" method="POST">
			{% csrf_token %} 
			<label>Title</label>
			<input type="text" name="title">
			<textarea name="blog" rows="8" cols="40"></textarea>
			<input type="submit" value="ENTER BLOG">
		</form>
	</body>
</html>