python_stack/django/leaderboard/apps/integration/urls.py
from django.conf.urls import url
from . import views

app_name = 'leaderboard'
urlpatterns = [
	url(r'^$', views.index, name = 'index')
]	

python_stack/django/leaderboard/apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^register/$', views.register, name = 'register'),
	url(r'^login/$', views.login, name = 'login')
]

python_stack/django/leaderboard/apps/ninjagold/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^process_money/$', views.process, name = 'process')
]

python_stack/django/leaderboard/leaderboard/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^leaderboard/', include('apps.integration.urls', namespace='leaderboard')), 
    url(r'^', include('apps.login_reg.urls', namespace='login')),
    url(r'^ninjagold/', include('apps.ninjagold.urls', namespace='ninjagold'))
]	

python_stack/django/leaderboard/apps/integration/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg.models import User

# Create your models here.
class Leaderboard(models.Model):
	user = models.OneToOneField(User)
	top_score = models.IntegerField()
	games_played = models.IntegerField()
	total_gold_earned = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

python_stack/django/leaderboard/apps/login_reg/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import messages
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')


# Create your models here.
class Manager(models.Manager):
	def validRegistration(self, userInfo):
		#registration form validations
		errors = []
		if not userInfo['first_name'].isalpha():
			errors.append('First name must only contain letters!')
		if len(userInfo['first_name']) < 1:
			errors.append('Please put a first name!')

		if not userInfo['last_name'].isalpha():
			errors.append('Last name must only contain letters!')
		if len(userInfo['last_name']) < 1:
			errors.append('Please put a last name!')

		if not EMAIL_REGEX.match(userInfo['email']):
			errors.append('Must be a valid email!')
		if len(userInfo['email']) < 1:
			errors.append('Please put a valid email!')
		if User.objects.filter(email=userInfo['email']):
			errors.append('A user with that email already exists!')

		if len(userInfo['password']) < 8:
			errors.append('Password must be at least 8 characters long!')
		if userInfo['password'] != userInfo['confirm']:
			errors.append('Passwords do not match!')

		if errors:
			return (False, errors)
		else:
			errors.append('Great! Thanks for registering '+userInfo['first_name']+'!')
			hashed = bcrypt.hashpw(userInfo['password'].encode(), bcrypt.gensalt())
			user = User.objects.create(first_name=userInfo['first_name'], last_name=userInfo['last_name'], email=userInfo['email'], pw_hash=hashed)
			return (True, user)

	def userExistsLogin(self, userInfo):
		#check to see if user already exists
		errors = []
		if len(userInfo['email']) < 1 or len(userInfo['password']) < 1:
			errors.append('Please fill in both an email and password!')
		elif not EMAIL_REGEX.match(userInfo['email']):
			errors.append('Make sure you have a valid email!')
		else:
			if User.objects.filter(email=userInfo['email']):
				hashed = User.objects.get(email=userInfo['email']).pw_hash.encode()
				password = userInfo['password'].encode()
				if bcrypt.hashpw(password, hashed) == hashed:
					errors.append('Success! Welcome, '+User.objects.get(email=userInfo['email']).first_name+'!')
				else:
					errors.append('Invalid password!')
			else:
				errors.append('Invalid Email!')

		if errors:
			return (False, errors)
		else:
			return (True, errors)
		



class User(models.Model):
	first_name = models.CharField(max_length=45)
	last_name = models.CharField(max_length=45)
	email = models.CharField(max_length=100)
	pw_hash = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	objects = Manager()

python_stack/django/leaderboard/apps/ninjagold/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

python_stack/django/leaderboard/apps/integration/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'ninjagold/index.html')

python_stack/django/leaderboard/apps/login_reg/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
	context = {
		'title': 'Login and Registration'
	}
	return render(request, 'login_reg/index.html', context)

def login(request):
	if request.method == 'POST':
		# print request.POST
		valid, response = User.objects.userExistsLogin(request.POST)
		# print valid
		# print response
		if not valid:
			for error in response:
				# print error
				messages.error(request, error)
				return redirect('login:index')
		else:
			return redirect('ninjagold:index')
	else:
		return redirect('login:index')

def register(request):
	if request.method == 'POST':

		valid, response = User.objects.validRegistration(request.POST)

		if not valid:
			for error in response:
				messages.error(request, error)
			return redirect('login:index')
		else:
			return redirect('leaderboard:index')
	else:
		return redirect('login:index')

python_stack/django/leaderboard/apps/ninjagold/views.py
from django.shortcuts import render, redirect

import random
import datetime

# Create your views here.
def index(request):
	#set counter to 0 if new session
	if 'count' not in request.session:
		request.session['count'] = 0
	else:
		pass

	#for displaying activities
	if 'action' not in request.session:
		request.session['action'] = []

	context = {
		'count': request.session['count'],
		'action': request.session['action']
	}

	return render(request, 'ninjagold/index.html', context)

def process(request):
	request.session['building'] = request.POST['building']
	building = request.session['building']

	#reset counter and activities list
	if building == 'reset':
		request.session['count'] = 0
		request.session['action'] = []

	#check which form
	if building == 'farm':
		farm_gold = int(random.randrange(10,21))
		request.session['count'] += farm_gold
		addAction(request, farm_gold, 'earned', 'farm')
		print farm_gold

	if building == 'cave':
		cave_gold = int(random.randrange(5,11))
		request.session['count'] += cave_gold
		addAction(request, cave_gold, 'earned', 'cave')
		print cave_gold

	if building == 'house':
		house_gold = int(random.randrange(2,6))
		request.session['count'] += house_gold
		addAction(request, house_gold, 'earned', 'house')
		print house_gold

	if building == 'casino':
		casino_gold = int(random.randrange(-50,51))
		request.session['count'] += casino_gold
		if casino_gold < 0:
			addAction(request, casino_gold, 'lost', 'casino')
		else:
			addAction(request, casino_gold, 'earned', 'casino')

		print casino_gold

	return redirect('ninjagold:index')

def addAction(request, num, action, place):
	#to display proper current date format
	timestamp = datetime.datetime.now()

	#insert relative activity info into action list
	if place == 'farm':
		request.session['action'].insert(0,['earn', 'Earned %d from the %s! %s' % (num, place, timestamp)])
	if place == 'cave':
		request.session['action'].insert(0,['earn', 'Earned %d from the %s! %s' % (num, place, timestamp)])
	if place == 'house':
		request.session['action'].insert(0,['earn', 'Earned %d from the %s! %s' % (num, place, timestamp)])
	if place == 'casino':
		if action == 'earned':
			earned = 'Earned %d from the casino! %s' % (num, timestamp)
			request.session['action'].insert(0,['earn', earned])
		elif action == 'lost':
			lost = 'Entered the casino and lost %d gold... Ouch %s' % (num, timestamp)
			request.session['action'].insert(0,['lost', lost])
	else:
		print "error"

	return redirect('ninjagold:index')

python_stack/django/leaderboard/apps/integration/templates/integration/index.html
{% extends "./layout.html"%}
{% block body %}
	{% if user %}
		{% if messages %}
			{% for msg in messages %}
				<p class="errors">{{ msg }}</p>
			{% endfor %}
		{% endif %}
<!-- 		<h1>Time to get rich {{ user }}!</h1>
 -->		<h1>Leaderboard</h1>
		<table>
			<tr>
				<th>Name</th>
				<th>Last Played</th>
				<th>Score</th>
			</tr>
		</table>
	{% else %}
		<h1>Time to get rich!</h1>
	{% endif %}
		{% block ninja %}{% endblock %}
{% endblock %}

python_stack/django/leaderboard/apps/integration/templates/integration/layout.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'integration/css/skeleton.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'integration/css/normalize.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'integration/css/styles.css' %}">

	</head>
	<body>
		{% block body %}{% endblock %}
	</body>
</html>

python_stack/django/leaderboard/apps/ninjagold/templates/ninjagold/index.html
{% extends "../integration/index.html" %}
{% block ninja %}
	<div class="wrapper">
		<h1>Ninja Gold</h1>
		<label>Your Gold: </label>
		<input type="text" value="{{ count }}">
		<form action="{% url 'ninjagold:process' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" name="building" value="reset">
			<input type="submit" value="RESET GOLD">
		</form>
		<div id="farm">
			<h3>Farm</h3>
			<p>(earns 10-20 golds)</p>
			<form action="{% url 'ninjagold:process' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="building" value="farm">
				<input type="submit" value="Find Gold!">
			</form>
		</div>
		<div id="cave">
			<h3>Cave</h3>
			<p>(earns 5-10 golds)</p>
			<form action="{% url 'ninjagold:process' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="building" value="cave">
				<input type="submit" value="Find Gold!">
			</form>
		</div>
		<div id="house">
			<h3>House</h3>
			<p>(earns 2-5 golds)</p>
			<form action="{% url 'ninjagold:process' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="building" value="house">
				<input type="submit" value="Find Gold!">
			</form>
		</div>
		<div id="casino">
			<h3>Casino</h3>
			<p>(earns/takes 0-50 golds)</p>
			<form action="{% url 'ninjagold:process' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="building" value="casino">
				<input type="submit" value="Find Gold!">
			</form>
		</div>
		<div id="activites">
			<h3>Activities:</h3>
        	{% if action %}
            	<ul>
                	{% for class, activity in action %}
                		<li class={{class}}>{{activity}}</li>
                	{% endfor %}
            	</ul>
        	{% endif %}
		</div>
	</div>
{% endblock %}